### ISSUE TITLE
Item Tables Overhaul

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#14]
Item tables are currently implemented with flexbox, and when the header row becomes too crowded, it becomes off-centered from its table contents. Consider this spellbook section:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/6222a348-ed15-4231-9f17-763bf640f56e)

- Rebuild list views so that becoming off-balance is impossible.
- Overflow should be handled in a more controlled and predictable way.
    - Current idea 💡 **specifically for Spellbook**:
        - Offload the primary column title (e.g., "Pact Magic 1st Level 🟠 1/1 ✏") to a standalone header row, where this content can expand out comfortably. In place of this text, the primary column should have the column title "Spell".
    - For all sheets, the "Name" column, like the item name itself, should truncate with ellipses "..." when compressed.
    - If there are too many columns and the sheet is not wide enough to accommodate them, a dedicated horizontal scrollbar should be provided for that tab (or list?)

Consider switching to CSS Grid for building these tables.
In the re-design, build with column selection possibilities in mind (#60).

**Comment by crash1115** [comment]
Gonna chuck this in here as a discussion point since it's relevant to header clutter. It would be kickass if the solution implemented here were designed in such a way that it could work in an environment where item list columns are customizable.

Very recently I was talking with my group about which things they didn't and didn't like about how the base dnd5e sheet displays items, and it became apparent to me that folks have different preferences for what information is easily visible. For instance, I don't need to have spell school or range listed as columns on the spellbook tab, and I would disable those if I could. Allowing people this flexibility might be a cool future feature.

**Comment by kgar** [comment]
Two complaints I've often seen in the wild:
- Tidy has too many tabs
- Tidy's tables are too crowded

With the way things are going, column selection is a very compelling feature add.

The way I see it, module developers will eventually be able to register columns and append content to existing columns. So, with our tables already feeling kind of crowded in their current state, providing extensibility like actor column selection will keep things sane.

And, column selection will synergize with the work currently being done on #58

**Comment by kgar** [comment]
I've looked at this long enough to know that table horizontal space should be resolvable with custom columns and better overflow control. CSS Grid vs Flexbox is not the real debate when fixing item tables. Grid has its own challenges and suffers from the same problems of overflow. Moreover, to support pure CSS animations, careful subgridding would be required, and even then, conditionally hiding columns via pure CSS would be off the table. I'm saying goodbye to this issue and will pursue custom columns and conditional column hiding by priority.
