### ISSUE TITLE
feat: Group Sheet for Tidy 5e

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#217]
There is not yet a Tidy 5e version of the Group sheet.
Determine the current feature set of the Group sheet and try to get a feel for the direction it is going in the dnd5e system.

The Tidy-ified version can start out as simply the Tidy 5e theme and the svelte rendering engine, and we could start looking for where/how to Tidy-ify the user experience once it is in the hands of users.

## Reference

https://discord.com/channels/1167985253072257115/1188926682153893968

**Comment by crash1115** [comment]
On the group sheet enhancements front, take a look at the pf2e party sheet for ideas for useful features. (I can drop screenshots if you don't PF2E). 

Showing things like passive perception and languages known on this thing would make it a great tool for GMs, and should still easily fit on there post tidy-fication.

**Comment by kgar** [comment]
I could use some screenshots with the sheet set up properly and demonstrating the features in action.

**Comment by crash1115** [comment]
Sorry for the delay, here's some screenshots!

**Overview**
The Overview tab shows the list of actors in the party. Each entry has the standard name and HP type info, but also shows senses and their perception score, plus some key defensive info (saves and AC), which skills they're trained in (roughly equivalent to proficiency in 5e), and how many hero points (inspiration) they have. The perception button can be clicked to GM roll a perception check. Clicking the character's name opens their sheet.

The top section also has tabs that display a list of all the languages the party knows. The number in parentheses is how many people have it, and hovering over each one shows a tooltip that shows the names of the people who have it. The other two tabs display the same things, but for trained skills instead of languages.

Saves and skills are probably overkill for a 5e implementation, but AC, senses and passive perception, and possibly languages would probably be great info for a DM to have quick access to.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/41387713/47c8ee19-eaf0-44ea-a715-6c06418c4f44)

**Stash**
The Stash tab is like the inventory on the current tab. It doesn't do anything super worth calling out. Notable difference is that it shows how much weight the party members are carrying and shows a sum of total party wealth, which is cool but not super necessary imo. There's a button to distribute coins between all party members; I honestly am not sure if the 5e sheet has that already or not. I wanna say it does, but not sure.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/41387713/3fee0274-df07-45ee-ad7a-fca342f42375)

The Exploration tab handles mechanics 5e doesn't have, so not super worth showing.

**Comment by kgar** [comment]
This is great information.
It would be nice to tool the Group actor in 5e to be useful for GMs and for players.
One thing I've been seeing, now that dnd5e 3.x is out, items actually transfer instead of duplicating when they are dragged.
The group sheet can act as a trading ground for items, which would be really neat.
Whenever I get above water with all the work to be done on the existing sheets, I'd like to make Tidy's group sheet cash in on all this good intel.

**Comment by crash1115** [comment]
Yeah I was really curious to see what they'd do with the group sheet in the 5e system once they got a chance to iterate on it some more. That hasn't happened yet (I can see why with all the stuff in 3.0, holy cow!) but maybe we'll see some improvements to it for further inspiration sometime between now and when you're ready to start tackling this.

I'll keep this ticket in the back of my mind as we're playing, and try to drop more ideas in here as I have them.

**Comment by kgar** [comment]
The base functionality of the Group Sheet as of 3.2.1 is really pretty good, especially the toolbar with Award, Place Members, and Short/Long Rest.
Adding the inspired pieces from PF2e, especially the detailed party member cards, would really fill this out in a good way.
It wouldn't be as pretty as the dnd5e 3.x default PC sheet yet, but Tidy will be adopting a new visual language this year 🤞, so that's a hop and a skip away. I could just focus on functionality and use the existing design to make something useful.

I think, before I make a group sheet, I will prioritize the recursively expandable containers in the inventory and container contents tabs. Then, I can reuse those gains when rolling out a useful group sheet with fully functional camp inventory.

**Comment by kgar** [comment]
Group Sheet Phase 1 is ready. I will be closing this issue when the Group Sheet is released.
Let's take additional features for Phase 2 as individual github issues to put on the Phase 2 milestone.

**Comment by kgar** [comment]
What a ride! Done!
