### ISSUE TITLE
Consumables can't be dragged onto owned vehicles

### ISSUE THREAD

**Issue by nolorfin** [kgar/foundry-vtt-tidy-5e-sheets#229]
Steps to reproduce:

1. Create a vehicle and make a player its owner.
2. Open a PC owned by the same player and try to drag a consumable item onto the vehicle.
3. The consumable item is not dragged.

Additionally, since this functionality is designed to move items from PCs to vehicles like horses, instead of just copying them, it would be nice if there was a function to move the items instead of copying them.

**Comment by kgar** [comment]
I will have to consider the part about moving items instead of copying them. I typically do not want to veer too far from the default behavior of Foundry / dnd5e when it comes to drag/drop behavior.

However, modules like "Item Piles" have item trading functionality like this.

**Comment by nolorfin** [comment]
We use Item Piles, but it only allows trading between players, not trading between actors owned by the same player, unless I'm missing something.

**Comment by kgar** [comment]
I apologize for the wait. I have begun troubleshooting this and was able to recreate the issue.
I will make sure to have a fix out in the next Tidy release for the consumable not successfully dropping onto the vehicle sheet.

As for the transfer of items by Move instead of Copy, it is complicated enough to merit its own feature request in a separate issue, so I can better prioritize and determine feasibility.

**Comment by kgar** [comment]
I've released a fix for this. Please have a look at your convenience, and let me know if consumables are now dropping successfully for your setup.

**Comment by nolorfin** [comment]
Works as a charm. Thank you!

**Comment by kgar** [comment]
I'm so glad to hear it!
Thank you for reporting the issue.

Closing as completed.
