### ISSUE TITLE
[Compatability Request] Party Inventory

### ISSUE THREAD

**Issue by JornieNonsubia** [kgar/foundry-vtt-tidy-5e-sheets#281]
There is no button to add item to party inventory.
Github link: https://github.com/teroparvinen/foundry-party-inventory

**Comment by kgar** [comment]
Thanks for reporting. As soon as I'm able, I will look into this.

**Comment by Gensokian** [comment]
Just as a little jump in; there is the "Group" actor which allows to group all people together. (Alltough not supported by Kgars Tidy)
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/3b2b720c-5328-4b80-958f-f57ee11d10b2)

Players even have a group Inventory then and can just yeet things in there
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/9213561/7f370164-59bd-4833-b500-2815f2f45b98)

**Comment by kgar** [comment]
Getting the conversation started here: https://github.com/teroparvinen/foundry-party-inventory/issues/24

Nice tip about the Group Sheet! 
On the topic of the Group Sheet, whenever New Tidy takes over the official Foundry Package ID, I will begin work on the Tidy Group Sheet. I'm also giving the group sheet some more time to evolve so I can get a clear picture of how it is meant to be used.

**Comment by kgar** [comment]
It seems like this is not going to become a reality. The module hasn't been updated since July 2023. 

Should we give it up?

**Comment by kgar** [comment]
I'm going to let this one go, because the module author has not responded after a long enough time. If something changes, perhaps we can reopen the issue and try to get it going again?

Tidy now has a group sheet that utilizes the full Tidy inventory feature set, including inline containers. You can create multiple groups with shared inventories for different purposes, etc. This is worth a look, I think.

I'm sorry I couldn't establish compatibility. The module dev community seems always to be in flux, with people coming and going.
