### ISSUE TITLE
Unable to open Monster stat blocks with SRD 3.0.1

### ISSUE THREAD

**Issue by Kraelll** [kgar/foundry-vtt-tidy-5e-sheets#326]
This was posted on the old GitHub repo by Skywolf-Software, but I will reproduce it here as I understand this is the current git repo. Original post [can be found here](https://github.com/sdenec/tidy5e-sheet/issues/812#issue-2122227009)

**Module Version:** v0.10.1

**Replication Steps**:
- Install 5e SRD 3.0.1
- Install TidySheet but do not activate it
- Disable all modules but 5E SRD
- Drag a monster from SRD/any other compatible compendium to your items area
- Double click the monster and whilst it's using the default sheet it will open as expected
- Enable the TidySheet module
- Attempt to open it again, but now stat blocks does not open

**Expected Behavior**
Monster and NPC sheets should be able to open when Tidy5e has been set as the default - but this is not the case. Sheets do not open at all.

**Screenshots**
N/A - unable to open sheets whilst NPC/Monster stat-blocks are set to use tidy5e as default

**Browser:**
Chrome, Firefox, and integrated VTT browser

**Foundry Version:**
Version 11 Stable - Build 315

**Game System:**
DnD 5e

**Comment by kgar** [comment]
Thanks for reporting.

Is "5e SRD 3.0.1" a module? Or is this referring to the [dnd5e 3.0.1 system version](https://foundryvtt.com/packages/dnd5e)?

If it's referring to the system version 3.0.1, Tidy5e Sheet 0.10.1 has a hard version cap set to 2.4.0-2.4.9, and enabling it should not be an option in dnd5e 3.x.

**Comment by Kraelll** [comment]
> Thanks for reporting.
> 
> Is "5e SRD 3.0.1" a module? Or is this referring to the [dnd5e 3.0.1 system version](https://foundryvtt.com/packages/dnd5e)?
> 
> If it's referring to the system version 3.0.1, Tidy5e Sheet 0.10.1 has a hard version cap set to 2.4.0-2.4.9, and enabling it should not be an option in dnd5e 3.x.

Hi there

That's correct - it was the system I was referring to 

If it's not yet compatible then that explains why it would be an issue. It did let me "use" the module in 0.10.0 which is where I noticed the problem, but after updating to 0.10.1 it did say it was no longer available

Is there a plan to make this compatible with 3.0.1? If so then I'm happy for this to be closed and will just patiently wait for the release

Appreciate the effort and development that goes into this module

Thanks

**Comment by kgar** [comment]
I am happy to report that the Tidy 5e Sheets rewrite is nearing V1 and will appear in the Foundry packages search as Tidy 5e Sheets version 1.0.0.

At first, it will be dnd5e 2.4.x compatible, since many of the current users are waiting for Midi-QoL and other modules to finish their 3.x upgrade.

For Tidy, I will be achieving minimal compatibility with dnd5e 3.x at first, and Tidy will grow into the additional features available in the new system, such as containers.

All of that is to say, look forward to Tidy availability in a matter of a few weeks, hopefully 🤞. In any case, I'm putting as much energy and time into this effort as I can while maintaining my balance with IRL/non-Foundry.

If interested, check out the readme on this repo for more information about progress. We also have a discord community (invite link on the readme) where I post frequent reports on how things are going.

I am looking forward to getting the rewritten sheets into your hands, and I hope they will serve you well.

This is tangentially related, but:
Tidy has historically not capped its version, which was a decision of the previous maintainers. As the new maintainer, I have opted to use the other approach where I cap version availability until I can confirm readiness of the module. So, my first release on the official package registry was 0.10.1, to prevent things like sheets not opening, since it would be pretty common for users to check out the new system version (3.x is pretty awesome 💪). I wouldn't want my module to stop people in their tracks.

**Comment by Kraelll** [comment]
> I am happy to report that the Tidy 5e Sheets rewrite is nearing V1 and will appear in the Foundry packages search as Tidy 5e Sheets version 1.0.0.
> 
> At first, it will be dnd5e 2.4.x compatible, since many of the current users are waiting for Midi-QoL and other modules to finish their 3.x upgrade.
> 
> For Tidy, I will be achieving minimal compatibility with dnd5e 3.x at first, and Tidy will grow into the additional features available in the new system, such as containers.
> 
> All of that is to say, look forward to Tidy availability in a matter of a few weeks, hopefully 🤞. In any case, I'm putting as much energy and time into this effort as I can while maintaining my balance with IRL/non-Foundry.
> 
> If interested, check out the readme on this repo for more information about progress. We also have a discord community (invite link on the readme) where I post frequent reports on how things are going.
> 
> I am looking forward to getting the rewritten sheets into your hands, and I hope they will serve you well.
> 
> This is tangentially related, but: Tidy has historically not capped its version, which was a decision of the previous maintainers. As the new maintainer, I have opted to use the other approach where I cap version availability until I can confirm readiness of the module. So, my first release on the official package registry was 0.10.1, to prevent things like sheets not opening, since it would be pretty common for users to check out the new system version (3.x is pretty awesome 💪). I wouldn't want my module to stop people in their tracks.

Excellent news! I'll patiently wait for the update to 3.x then - thanks so much for clarifying, looking forward to seeing TidySheets 1.0.0 :)

I'll close this as it's already in the works
