### ISSUE TITLE
[Compatibility Request] Autocomplete Inline Properties

### ISSUE THREAD

**Issue by 413120** [kgar/foundry-vtt-tidy-5e-sheets#345]
I believe the original tidy5e sheet had full compatiblity with the "Autocomplete Inline Properties" module. It adds a small ui in certain fields in item sheets that display the available data properties one might want to use in roll formulas, et c. I'm not sure if it's still maintained as there's only been one update in the last year, but it does still function with the default sheet and the DAE sheet's fields, so I'm hoping so.

The module's github is [https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties](https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties)

**Comment by kgar** [comment]
Hello, thank you for reporting.

The New Tidy sheets are their own thing, so compatibility has to be established between it and other modules.

I will get the conversation started on that module.

Currently, I am working on dnd5e 3.x compatibility, so that is consuming a lot of my time. In any case, compatibility would need to be established over on the AIP module.

**Comment by kgar** [comment]
Starting the conversation here: https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/issues/512

**Comment by kgar** [comment]
I'm probably going to let this one go. The module hasn't been update, and the cross-post on the module never received a reply from the author.

**Comment by kgar** [comment]
I am sorry to say, I don't expect anything to come of this. I haven't heard back for a long time from the module author :/
