### ISSUE TITLE
[Feature Request] Container Icons Tab or Field like in the new default sheet.

### ISSUE THREAD

**Issue by SirAron111** [kgar/foundry-vtt-tidy-5e-sheets#418]
Ok while I love the cleanliness and compact few, having the icon buttons to open and close containers which display how full they are is a real good feature of the new default 5e sheet and I would love to be able to toggle this feature on in the tidy sheet as well.
Especially if you have modules like midiqol or so which block the list views icon with an auto roll effect it doesn't open the container unless you select it via right click etc.

![Unbenannt](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/39855956/38453554-b0a8-4919-a899-36ecd66cfaac)

(Or make it its own tab or so that shows bag contents etc)

**Comment by kgar** [comment]
My existing plans were to do something similar to pf2e's container views:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/8ec8f440-2e3e-4956-a21c-da60f9da5a67)

Basically, you'd be able to peek into the container directly from the item sheet, via a Box icon button.

Tidy has a lot of work to do to support containers yet, so I'll have to come back to this issue as soon as the initial offering is ready, and we can discuss where to go from there.

**Comment by SirAron111** [comment]
Ye. Having tidy containers would be nice. Currently, they look like this with tidy enabled.
![Unbenannt](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/39855956/fe17c9d0-adeb-4b60-8362-02088f72f994)

Also, the drop-down seems like a decent solution, but on big containers or inventories with lots of stuff it will feel cluttered. Having the separate small sheet pop out via a button allows for faster sorting and drag and dropping of items between container and inventory. I have players that collect literally everything, so I don't want to imagine what the drop-down in their inventory would look like and how annoying it would be to try and drop an item in and out of it if you have to hold and drag it while scrolling through the 100+ item long drop down

Having a button/ icon of items classified as containers added to a small side window or so would be nice. Like the small widgets on the default sheet on the side or as icons with a specified and dedicated spot on the sheet's top. If that is possible.

**Comment by kgar** [comment]
That makes sense.
Some thoughts about how we might visualize this.
I'm building up a convention of being able to toggle parts of a sheet tab with utility toolbar buttons. One example is the legendary toolbar toggle:
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/d813e6a7-e514-4cc9-adfa-711a2d8f6251)

I could see us putting a container-specific view toggle on the Character Inventory tab to show/hide a paneled default-like container toolbar, where left-click opens the container edit screen. That would actually be really simple to implement and unintrusive for those who don't want it.

When making these toolbar buttons, one thing I have to decide is this:
- Does the button apply to all character sheets for the target user? (a user preference that is saved on the user document)
- Does the button apply to the current sheet, only? (a Tidy flag on the actor itself)
- Do I manage this state in some other new way?

There is a growing convention of putting this kind of preferential toggle on User Preferences instead of the sheet itself, and I think that will work best for container view toggle. If we go that route, then Tidy will remember your preference and apply it on any Character sheet that you specifically open. Meanwhile, your players would specify their own preference if they wish to show or hide the container section.

What are your thoughts on this?

**Comment by SirAron111** [comment]
That sounds brilliant. Being able to toggle things on and off is genius for people who love to customize and organize. A good fit for a Tidy Sheet Module like this. I really liked the Legendary Toggle, as it allowed me to only have it visible on mobs that actually have these actions. Opening such a tab box via toggle that makes the Container tab appear similar to the default sheet would be really great.

As for your concerns:
1. Does the button apply to all character sheets for the target user? (a user preference that is saved on the user document)
- In this case it only would be needed only on Character sheets as mobs don't care about containers. Vehicles might and some specific npcs might like  companion or so but those two aren't the priority here not that they have an inventory tab to begin with (which is annoying when you kit out a boss with magic items, and they are all in the same tab as abilities etc)

2. Does the button apply to the current sheet, only? (a Tidy flag on the actor itself)
- most likely a flag so you can individualize each sheet for this case. Some players might it turned on, some might not, so actor specific would be good.

3. Do I manage this state in some other new way?
- cant say much about that since i can't program but making it a toggle button in the inventory tab toolbar sounds clean and easy. And making it open up a box space with the various containers of a character appear like the default 5e 3.0 sheet would be perfect, my organizer crazy wizard player loved these bag options and the fact they even showed how full they were. His only complaint was the money transfer tab was a bit cluttered XD.

As a DM I like being able to set things as default via configs, so my players don't have to go through all the settings individually themselves (Let them play not work ^^).  So I use modules like "Forced Settings and keybinds etc" to even simplify the options' menu, but I always use the soft lock feature as it allows them to later if they want to change something, can change it to their preferred use case.
