### ISSUE TITLE
[Suggestion] sharable/linkable group containers.

### ISSUE THREAD

**Issue by SirAron111** [kgar/foundry-vtt-tidy-5e-sheets#644]
Not sure if this is the right place for this suggestion, but is it possible to make a container item appear on every player character's sheet when one person has it equipped? Or to make it so that an item can be linked to a container like actor so that everyone with the item on their sheet can access said container actor by clicking on the item on their sheet so it opens up a container window?
This would be really useful for containers that each party member accesses frequently, like a Bag of Holding, a carriage's cargo or a Keeps Storage etc? Because it's a pain for my players to constantly having to ask who has the bag of holding right now, is x item in the bag atm etc. especially since dragging and dropping items always only dupes them, never moves them like the containers do in dnd 5e now.

**Comment by kgar** [comment]
This kind of special item would be the purview of a specialized module, I think. 

However, consider this idea: some have suggested using a Group Actor's inventory as the party / camp inventory. This is a great way to provide loot, coinage, and shared resources. It should also support containers like a bag of holding.

**Comment by SirAron111** [comment]
Ah ok good to know. Hope someone makes such a module some day. Because using the Group Actor for this is a similar problematic with items just duplicating on switch back and forth unlike containers that actually move things.

**Comment by kgar** [comment]
Containers moving things is unfortunately an illusion of how they are coded. They give the impression that they are moving items from container to actor and vice versa. The truth is, dnd5e is just putting on or taking off a container ID for the dragged item. It's not actually moving data. It does feel right to move rather than copy items, and at a system level, it would be good if they coded it so items actually transferred when dragged between actors. Maybe someday. I'm sure someone has requested it on the system repo.
