### ISSUE TITLE
`calculateDeterministicBonus` doesn't always handle non-deterministic tokens correctly.

### ISSUE THREAD

**Issue by mrguenther** [kgar/foundry-vtt-tidy-5e-sheets#667]
I'm seeing an issue similar to one that was previously reported against the original `tidy5e-sheet` module and then fixed: https://github.com/sdenec/tidy5e-sheet/issues/668

When a player uses DAE to enable a _Bless_ effect adding `+1d4` to their attack bonuses, the `calculateDeterministicBonus` function causes an error by passing an empty array into `Roll.fromTerms()`. This is because it prunes any non-deterministic terms, which often works but can still cause errors in certain cases.

This most common failure mode is when the entire formula is non-deterministic, in which case `Roll.fromTerms()` attempts to parse an empty formula. That's quite simple to fix—just return 0 instead of parsing anything—but there are unfortunately much more nuanced ways in which the logic can theoretically fail. If someone has a `system.bonuses.rsak` value of `1 + 1d4 * 2`, for example, the current logic will prune out the `1d4` token and attempt to evaluate `1 + * 2`. That error will be significantly more complicated to fix since it will require us to generate a syntax tree for the formula and prune non-deterministic expressions from it.

This is the location of the bug: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/blob/68b444c38359549a58e1947e341d3f0c6662eafa/src/utils/formula.ts#L225-L229

I have a PR ready to fix the most common failure case and catch the more nuanced version, logging the latter as a warning. I don't think fixing the syntax-tree issue is likely to be very high priority given the ratio of effort required to severity of the bug, but I do want to make sure it's at least recorded as a known issue in the short term.

**Comment by kgar** [comment]
The short-term fix looks good, provided a few adjustments that keep to the spirit of the fix but resolve compiler and runtime issues.

Because Tidy does so many different things across a very broad spectrum, it will be some time before I can dedicate time to studying the roll API and puzzling through the best long-term approach. It's a worthy endeavor, but there's just a big stack of things to do that are higher in priority.

Though it is just a convenient UI feature in the end, it would be nice if it handled a majority of common cases.

This might be an area of the code base where I look to the community for some help in a follow-up issue.

**Comment by kgar** [comment]
Tidy V4.5.1 has the fix.

**Comment by mrguenther** [comment]
Perfect; thanks!
