### ISSUE TITLE
[BUG] Hit Point Max does not auto-update on level up. Requires Configure HP, which increases current HP twice

### ISSUE THREAD

**Issue by danmartinez78** [kgar/foundry-vtt-tidy-5e-sheets#730]
Copying from https://github.com/sdenec/tidy5e-sheet/issues/789 as it seems it was never actually moved and the issue still persists through the latest versions of tidysheet

Module Version: v0.9.17

So you have Current HP, and Max HP, which looks like 0/40 if you're unconscious, or 40/40 if you're at full health.

Lets say you level up and your HP increases by 8. This should bring you to 48/48, but instead it only updates your current HP, and puts you at 48/40, which doesn't make any sense. To bring your HP Max to what it should be, you need to hit the Cog beneath your HP to open "Configure Hit Points", and then delete the HP in the popup, and you'll see it gets reset to what it should be. However, when you click save, it will update your current HP by that amount for a second time. So now your HP looks like 56/48.

If this bug could be fixed that would be great. Ideally when you level up it should just automatically boost your HP and Max HP by the same amount, so that you don't have to take a trip to the Configure HP window.

**Comment by kgar** [comment]
This Tidy 5e Sheets as a module is presenting the information and allowing changes to individual fields on the sheet. It is not managing levels up. It also does not decide how much HP is being added to the current value or the max. Even the weird thing where current HP goes up by the new Max while an overridden Max stays the same (48/40) is not this sheets module. It's the system and/or a module affecting levels up. Updates go to the actor, and the sheet pulls data from the actor each time the actor changes. So there's no logic in Tidy to increase the health bar on a level up.

It sounds like the core problem is that Max HP is somehow getting set to a value when it should be blank in order to allow for the advancement-based max HP increases to go into effect. I recognize this issue from old Tidy, both as a user and when rewriting it. I just haven't had issues with this since old Tidy, because the new setup requires a person to specifically change the Max HP override in order to ignore HP advances. In old Tidy, Max HP Override could get accidentally set when changing other fields.

We can still try to figure out what's going on and see if there's some resolution, but having not had any issues with this since Tidy V1 (except for when the Max HP override was already set beforehand), I don't think a code change will solve the problem.

What is the current approach being used for levelling up?

Has the issue recurred for a given character while on the new sheets module?

Is the "Allow HP Max Override on Character" turned on? If so, it might be good to disable it, because it's entirely possible someone may accidentally change the max, causing it to shift from "calculated per advancements" to "max HP override."
![image](https://github.com/user-attachments/assets/19ebcdcc-96bf-46ab-8830-a87a84dc4a03)

If I go in and level up a character like this:
![image](https://github.com/user-attachments/assets/f24e4a6b-fb18-4797-8cee-ad81fed4e22d)

By the end, their HP has adjusted accordingly:
![image](https://github.com/user-attachments/assets/0cbbd05d-20c8-47be-8aa9-30fedb29b3d2)

**Comment by kgar** [comment]
Any further discussion on this?
I still have not encountered this issue in all my testing since this was posted.

**Comment by kgar** [comment]
I haven't heard back, and I cannot reproduce this error. Closing for now, but if you want to continue the discussion, feel free to reopen this issue or post a new one.
