### ISSUE TITLE
Feature Request: Ability to configure expanded activity list.

### ISSUE THREAD

**Issue by tposney** [kgar/foundry-vtt-tidy-5e-sheets#861]
Midi now has activities that can be marked as automation only and so should not appear in the expanded item activity list.

With the core dnd5e sheet I can override asset.prepareSheetItem which returns (amongst other things) a list of activities to display in the expanded activity list. I could not find a similar option in tidy sheets. It's not a huge issue, but does improve the overall appearance.

**Comment by kgar** [comment]
Are the activities themselves distinct from other activities as found in `CONFIG.DND5E.activityTypes`? If so, there's a `configurable` boolean option that can hide and prevent messing with activities. The prime example is the `order` activity type.

I took a look around, and I see that Tidy also has `_prepareItems` and `_prepareItem`, like the default sheets, but Tidy is pulling activities directly from `item.system.activities.contents` in its templating rather than preparing a list of eligible activities. This is a product of me recreating default sheet functionality from scratch without reading through their implementation very closely. 

In essence, on each `itemContext` member, you'd like an `activities` array which represents the subset of activities to include when expanding item details/activities on the character sheet? Is there anything else needed beyond that? Or will this allow you to exclude the automation activities? On the Tidy side, I can respect the final array of activities when rendering available activities.

What about in item sheets' activity tabs? Is something similar needed?

**Comment by tposney** [comment]
The activities are all found in CONFIG.DND5E.activityTypes.

**Comment by tposney** [comment]
I was not aware of the boolean option, which is it? I can use that instead perhaps.
I really should read from top to bottom of your post before responding

**Comment by kgar** [comment]
> That's exactly what I want and is sufficient - essentially that's exactly what the dnd5e sheet does - it looks at the _prepareItem activity list.
> 
> For the item sheet activities tab it should always be all of the activities - else you could not remove an automation activity if you wanted to.

Whatever we do, I'll make sure to achieve parity here. What props do you need on the activity list objects? I imagine 'id', but anything else?

**Comment by kgar** [comment]
Here's a build with activities arrays in PC, NPC, Vehicle, Group, and Container `itemContext` objects.

[tidy5e-sheet.zip](https://github.com/user-attachments/files/17967308/tidy5e-sheet.zip)

One thing to note: because Tidy has recursive inline container support, there will be item contexts that are nested further down whenever there is a container.

The itemContext property is `containerContents`, and inside, there will be another `itemContext` with item contexts. Inside that, there could be another `containerContents` and so on. I can provide more details later if you need them. Just let me know.

**Comment by kgar** [comment]
When you're good with the build, I'll get it ready for release. I can make additional adjustments as needed. Just let me know.

**Comment by kgar** [comment]
I'm happy to hear it! Thanks for reaching out about this.

Here's the hook, in case you'd prefer to use it: https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/TidyHooks.html#tidy5eSheetsGetActivitiesForPlay

Tidy V7.2.1 has these updates now.

**Comment by tposney** [comment]
I'll use the hook instead much cleaner.

**Comment by tposney** [comment]
All working fine - thanks
