### ISSUE TITLE
Feature Request: Show/Hide Not Proficient (PC sheet toggle)

### ISSUE THREAD

**Issue by roguedevjake** [kgar/foundry-vtt-tidy-5e-sheets#91]
NPCs have a toggle under their skills that allows them to show/hide non proficient skills. 

I would love for PC's to have the same toggle (even if the default is inverse to that of the NPC and shows all skills by default).

5e (and the One D&D playtest) explicitly don't let you roll a skill you aren't proficient in, you roll the ability check instead. This matters when it comes to spells or abilities that buff a skill but not an ability check or buff an ability check and give a bonus to a skill. 

**Citing the PHB**
`Without proficiency in the skill, the individual makes a normal ability check.`

`the DM might ask for a Strength (Athletics) check. If the character is proficient in Athletics, the character’s proficiency bonus is added to the Strength check. If the character lacks that proficiency, he or she just makes a Strength check.`

I run RAW and like the interaction with spells like pass without trace, but even outside of that it is nice for sheet parity and cleanliness.

**Comment by kgar** [comment]
On the way. It'll be in tonight's release if all goes well.

**Comment by kgar** [comment]
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/719bd00d-ed11-43b1-b1c7-69b972d4c7c8)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/feed5653-272f-4e6e-8500-87d7d60242ee)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/3aca0d41-a70d-4559-99ad-d64d44eaef87)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/cf0ce61f-7884-400b-96e9-ed97e03e4c85)

### Breaking Change

The flag "npcSkillsExpanded" is now just "skillsExpanded". This is owing to the generic nature of this flag to be used across various sheet actor types, rather than having a separate flag per actor type.

This means any existing toggles will be reset to default for NPCs. Apologies for any inconvenience. Either a member of the community skilled at macros or I can come up with a one-time-use migration macro if there is a great enough need for it.

**Comment by kgar** [comment]
This is now released in [0.1.17](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v0.1.17)

**Comment by kgar** [comment]
Closing as completed.
