### ISSUE TITLE
FYI: CSS conflict with Monk's Little Details

### ISSUE THREAD

**Issue by ctbritt** [kgar/foundry-vtt-tidy-5e-sheets#94]
Not really a problem for you, but just an FYI: When the CSS settings are checked in Monk's Little Details, you can't see the text in for the drop-down menu in the light setting for the sheet. 

![CleanShot 2023-11-29 at 13 44 44](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4516034/9b9b4254-a98d-47d3-802e-b24a60b2cdb8)

Again, not your problem but just an FYI if anyone else is having this issue. Turning off these settings in MLD fixes the issue: 

![CleanShot 2023-11-29 at 13 53 16@2x](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4516034/4c7e78f3-e082-4fcf-8d54-a85116fe1d92)

**Comment by kgar** [comment]
Thanks for reporting! 
I might be able to do something about this in Tidy, since we generally want the context menu to stay in line with the Tidy theme settings.

**Comment by kgar** [comment]
I think there's a middle ground. If I increase specificity on my context menu CSS by a single class, I think that gets us generally to where MLD was intending to be:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/c3815eb5-f053-434d-a927-006245efa530)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/8e2b6897-5c32-446c-8771-5f17b4942694)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/16d48269-5c8e-42de-a0a8-ac10a3b8e5b1)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/734c4a4c-882d-4818-9d78-419ede68f786)


The default sheet context menu with MLD CSS applied, for reference:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/dabaea21-b3a4-4c1f-ad33-d09347a87d2c)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b3d4258d-ffae-4bf4-b714-5e07d09fb3df)

I can ship this update in the upcoming release.

**Comment by kgar** [comment]
I was able to figure out the issue and restore the Tidy 5e look of the context menu, even when MLD is in use:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/0ca2e692-c198-4318-8210-b79f5eea653e)

And it leaves the other sheets with the MLD context menu intact:

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/fff4f3e4-65fb-4850-a3d4-d051860a12ac)

I think the core issue is that MLD's CSS changes are not taking Tidy 5e into account, which is perfectly ok. That really makes this the best solution, because users can still enjoy the other CSS changes without it making their context menu unreadable.

**Comment by ctbritt** [comment]
Nice! thanks for doing that!

**Comment by kgar** [comment]
Gladly! The next release is in a day or so.

**Comment by kgar** [comment]
The release is out. When able, have a look. If it is resolved, feel free to close the issue. Thanks again for finding this. Another user was experiencing it but couldn't figure out why. They send their thanks 🙏

**Comment by kgar** [comment]
Closing as completed. Thanks again for finding this
